Feature/filtering generation cleanup
sotopia-lab/sotopia-pi pull request #180
Opened 2024-03-13 07:14 UTC by sharonwx54

Closes # 

## 📑 Description
Using this PR instead as the previous one become really ugly after I resolve all conflicts. Not sure why the changed files goes to hundreds. I believe all passwords are removed as well. 

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ] Ready for code review

## ℹ Additional Information

2024-03-13 07:15 UTC, lwaekfjlk requested changes
can you help run "black ." to make sure that the code style follows black? and run the pre-commit check.

2024-03-13 07:22 UTC, lwaekfjlk commented on data_process/utils/interactive_filtering.ipynb
can you convert this ipynb into python file so that our repo would not be considered as mainly made up of ipynb?

2024-03-14 01:57 UTC, sharonwx54 commented on data_process/utils/interactive_filtering.ipynb
Sure will do it now.

2024-03-14 01:58 UTC, sharonwx54 commented
> can you help run "black ." to make sure that the code style follows black? and run the pre-commit check.

The black. run changes 79 files, not all of them owned by me. I would only commit those I changed in this PR, unless we intended to use the formatted files for all of those.

2024-03-14 02:58 UTC, lwaekfjlk commented
sure, that black would be good.

2024-03-14 02:58 UTC, lwaekfjlk commented
Should we abort #164 ?

2024-03-14 06:26 UTC, closed without merging